### ISSUE TITLE
Theme is not changing by given steps.

### ISSUE THREAD

**Issue by narendramrth30** [dehamzah/starter-theme-openedx#1]
We have deployed openedx on azure using microsoft stamp deployment. We deployed the ficus release. We want to change the themes. We have followed all the steps but it is not working. We have followed also the openedx documentation. but  the theme is not changing. We are not getting any error while doing the steps you have given.

**Comment by dehamzah** [comment]
I never try openedx on azure using microsoft stamp deployment.
but it should work if the configuration files is in the same location as normal deployment.

**Comment by narendramrth30** [comment]
Hey Thank you Dede!!, We have successfully applied theme by putting the files in the location you have mentioned.
